config/routes.rb
Rails.application.routes.draw do
  
  resources :stocks, :processings, :offices, :homes, :orders

  root 'homes#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end

  def destroy
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end

  def destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def index
  end

  def show
  end

  def destroy
  end
end

app/controllers/processings_controller.rb
class ProcessingsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end

  def destroy
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/processings_helper.rb
module ProcessingsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/homes/create.html.erb
<h1>Homes#create</h1>
<p>Find me in app/views/homes/create.html.erb</p>

app/views/homes/destroy.html.erb
<h1>Homes#destroy</h1>
<p>Find me in app/views/homes/destroy.html.erb</p>

app/views/homes/edit.html.erb
<h1>Homes#edit</h1>
<p>Find me in app/views/homes/edit.html.erb</p>

app/views/homes/index.html.erb
<div class="home-box center-block" style="text-align:center;">
<h1>還是信為，最安心</h1>
<div class="col-md-3">
<img width="266" height="400" src="http://www.swdurables.com/wp-content/uploads/2014/05/DSC_0053.jpg" class="attachment-full img-thumbnail" alt="DSC_0053">
<h3>Jason</h3>
</div>
<div class="col-md-3">
<img width="266" height="400" src="http://www.swdurables.com/wp-content/uploads/2014/05/DSC_0057.jpg" class="attachment-full img-thumbnail" alt="DSC_0057">
<h3>Stephanie</h3>
</div>
<div class="col-md-3">
<img width="266" height="400" src="http://www.swdurables.com/wp-content/uploads/2014/05/DSC_0051.jpg" class="attachment-full img-thumbnail" alt="DSC_0051">
<h3>Ivan</h3>
</div>
<div class="col-md-3">
<img width="266" height="400" src="http://www.swdurables.com/wp-content/uploads/2014/05/DSC_0062.jpg" class="attachment-full img-thumbnail" alt="DSC_0062">
<h3>Melody</h3>
</div>
<br>
<br>
<br>
</div>

app/views/homes/new.html.erb
<h1>Homes#new</h1>
<p>Find me in app/views/homes/new.html.erb</p>

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/homes/update.html.erb
<h1>Homes#update</h1>
<p>Find me in app/views/homes/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swdurables</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <link href="./css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="./css/sticky-footer-navbar.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to '信為の小網站', homes_path, class:'navbar-brand' %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller]=='processings'? 'active':'inactive'%>"><%= link_to '型男現場加工區',processings_path %></li>
            <li class="<%= params[:controller]=='offices'? 'active':'inactive'%>"><%= link_to '美女專用辦公室',offices_path %></li>
            <li class="<%= params[:controller]=='stocks'? 'active':'inactive'%>"><%= link_to '帥哥倉庫管理', stocks_path %></li>
          </ul>
          <form class="navbar-form navbar-right" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">搜尋</button>
      			<select class="form-control">
				  <option>全部</option>
				  <option>出貨</option>
				  <option>加工</option>
				</select></td>
	      </form>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">秘密功能<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">訂飲料</a></li>
                <li><a href="#">買點心</a></li>
                <li><a href="#">看八卦</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">個人功能</li>
                <li><a href="#">發佈自己的八卦</a></li>
                <li><a href="#">徵求某人的八卦</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- Begin page content -->
    <div class="container">
  	   <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">Copyrights &copy Swdurables 2015</span><br><span class="text-muted">Designed by GoodNine</span>
      </div>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="javascripts/bootstrap.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/offices/create.html.erb
<h1>Offices#create</h1>
<p>Find me in app/views/offices/create.html.erb</p>

app/views/offices/destroy.html.erb
<h1>Offices#destroy</h1>
<p>Find me in app/views/offices/destroy.html.erb</p>

app/views/offices/edit.html.erb
<h1>Offices#edit</h1>
<p>Find me in app/views/offices/edit.html.erb</p>

app/views/offices/index.html.erb
<div class="container" id="wrap">
  <div class="page-header">
    <h1>美女專用辦公室</h1>
  </div>
  <div class="header lead" id="wait">待出貨  <span class="caret"></span><%= link_to '新訂單', new_order_path, class:'btn btn-success pull-right' %></div>
  <table class="table table-hover">
  	<tr class="table_header">
  		<td style="width:10%">圖號</td>
  		<td style="width:10%">數量</td>
  		<td style="width:10%">期限</td>
      <td style="width:70%"></td>
  	</tr>
  	<tr class="table_content">
  		<td>132592859869</td>
  		<td>20</td>
  		<td><p style="color:red; font-weight:bold">3</p></td>
  		<td><button class="btn btn-success"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span> 上傳圖片</button> <button class="btn btn-primary">編輯資料</button> <button class="btn btn-warning">回報問題</button></td>
  	</tr>
  </table>
  <p class="lead" id="wait">待加工</p>
  <table class="table table-hover">
  	<tr class="table_header">
  		<td style="width:10%">圖號</td>
  		<td style="width:10%">數量</td>
  		<td style="width:10%">期限</td>
  		<td style="width:70%"></td>
  	</tr>
  	<tr class="table_content">
  		<td>132592859869</td>
  		<td>20</td>
  		<td><p style="color:red; font-weight:bold">3</p></td>
  		<td><button class="btn btn-success"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span> 上傳圖片</button> <button class="btn btn-primary">編輯資料</button> <button class="btn btn-warning">回報問題</button></td>
  	</tr>
  </table>
  
  <p class="lead" id="doing">包裝中</p>
  <div class="table-responsive">
      <table class="table table-hover">
      	<tr class="table_header">
      		<td style="width:10%">圖號</td>
      		<td style="width:8%">位置</td>   		   
      		<td style="width:9%">負責人</td>
      		<td style="width:10%">開始於</td>
      		<td style="width:10%">最後更新</td>
      		<td style="width:25%">狀況</td>
      		<td ></td>
      		<td></td>
      	</tr>
      	
      	<tr class="table_content">
      		<td>1325928<p id="enhanced_text">59869</p></td>
      		<td id="enhanced_text">A箱</td>
      		<td>
      			<select class="form-control">
				  <option>文清</option>
				  <option>阿輝</option>
				  <option>丁丁</option>
				</select></td>
      		<td><p>11:39</p><p>12.13.2014</p></td>
      		<td><p>14:20</p><p>12.13.2014</p></td>
      		<td><textarea class="form-control" rows="3"></textarea></td>
      		<td><button class="btn btn-danger">暫停包裝</button></td>
      	</tr>
      	<tr class="table_content">
      		<td>1325928<p id="enhanced_text">59869</p></td>
      		<td id="enhanced_text">B箱</td>
      		<td>
      			<select class="form-control">
          <option>文清</option>
          <option>阿輝</option>
          <option>丁丁</option>
				</select></td>
      		<td><p>11:20</p><p>12.13.2014</p></td>
      		<td><p>14:20</p><p>12.13.2014</p></td>
      		<td><textarea class="form-control" rows="3"></textarea></td>
      		<td><button class="btn btn-danger">暫停包裝</button></td>
      	</tr>
      </table>
  </div>
  
  
  <p class="lead" id="doing">加工中</p>
  <div class="table-responsive">
      <table class="table table-hover">
      	<tr class="table_header">
      		<td style="width:10%">圖號</td>
      		<td style="width:8%">剩餘</td>
      		<td style="width:9%">加工機</td>      		   
      		<td style="width:9%">負責人</td>
      		<td style="width:10%">開始於</td>
      		<td style="width:10%">最後更新</td>
      		<td style="width:25%">狀況</td>
      		<td></td>
      	</tr>
      	
      	<tr class="table_content">
      		<td>1325928<p id="enhanced_text">59869</p></td>
      		<td style="font-size:24px;"><sup id="enhanced_text">3</sup>&frasl;<sub>20</sub></td>
      		<td>
      			<select class="form-control">
				  <option>內徑1</option>
				  <option>內徑2</option>
				  <option>內徑3</option>
				  <option>內徑4</option>
				  <option>內徑5</option>
				</select>
      		</td>
      		<td>
      			<select class="form-control">
				  <option>志翰</option>
				  <option>君翰</option>
				  <option>老師傅</option>
				</select></td>
      		<td><p>11:20</p><p>12.13.2014</p></td>
      		<td><p>14:20</p><p>12.13.2014</p></td>
      		<td><textarea class="form-control" rows="3"></textarea></td>
      		<td><button class="btn btn-danger">暫停加工</button></td>
      	</tr>
      	<tr class="table_content">
      		<td>1325928<p id="enhanced_text">59869</p></td>
      		<td style="font-size:24px;"><sup id="enhanced_text">3</sup>&frasl;<sub>20</sub></td>
      		<td>
      			<select class="form-control">
				  <option>內徑1</option>
				  <option>內徑2</option>
				  <option>內徑3</option>
				  <option>內徑4</option>
				  <option>內徑5</option>
				</select>
      		</td>
      		<td>
      			<select class="form-control">
				  <option>志翰</option>
				  <option>君翰</option>
				  <option>老師傅</option>
				</select></td>
      		<td><p>11:20</p><p>12.13.2014</p></td>
      		<td><p>14:20</p><p>12.13.2014</p></td>
      		<td><textarea class="form-control" rows="3"></textarea></td>
      		<td><button class="btn btn-danger">暫停加工</button></td>
      	</tr>
      </table>
  </div>
  
  <p class="lead" id="finished">已加工完成</p>
  <table class="table table-hover">
    <tr class="table_header">
      <td style="width:10%">圖號</td>
      <td style="width:10%">數量</td>
      <td style="width:10%">結束於</td>
      <td style="width:10%">加工機</td>
      <td style="width:10%">負責人</td>
      <td></td>
    </tr>
    
    <tr class="table_content">
      <td>132592859869</td>
      <td>20</td>
      <td><p>16:35</p><p>12.13.2014</p></td>
      <td>內徑3</td>
      <td>志翰</td>
      <td><button class="btn btn-warning">回報問題</button></td>
    </tr>
    
  </table>
  
  <p class="lead" id="finished">已包裝完成</p>
  <table class="table table-hover">
    <tr class="table_header">
      <td style="width:10%">圖號</td>
      <td style="width:10%">數量</td>
      <td style="width:10%">結束於</td>
      <td style="width:10%">位置</td>
      <td style="width:10%">負責人</td>
      <td></td>
    </tr>
    
    <tr class="table_content">
      <td>132592859869</td>
      <td>20</td>
      <td><p>16:35</p><p>12.13.2014</p></td>
      <td>B箱</td>
      <td>文清</td>
      <td><button class="btn btn-warning">回報問題</button></td>
    </tr>
    
  </table>
</div>    

app/views/offices/new.html.erb
<h1>Offices#new</h1>
<p>Find me in app/views/offices/new.html.erb</p>

app/views/offices/show.html.erb
<h1>Offices#show</h1>
<p>Find me in app/views/offices/show.html.erb</p>

app/views/offices/update.html.erb
<h1>Offices#update</h1>
<p>Find me in app/views/offices/update.html.erb</p>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/processings/create.html.erb
<h1>Processings#create</h1>
<p>Find me in app/views/processings/create.html.erb</p>

app/views/processings/destroy.html.erb
<h1>Processings#destroy</h1>
<p>Find me in app/views/processings/destroy.html.erb</p>

app/views/processings/edit.html.erb
<h1>Processings#edit</h1>
<p>Find me in app/views/processings/edit.html.erb</p>

app/views/processings/index.html.erb
<div class="container" id="wrap">
  <div class="page-header">
    <h1>型男現場加工區</h1>
  </div>
  <div class="header lead" id="wait">待加工</div>
  <table class="table table-hover">
  	<tr class="table_header">
  		<td style="width:10%">圖號</td>
  		<td style="width:10%">數量</td>
  		<td style="width:10%">期限</td>
  		<td style="width:70%"></td>
  	</tr>
  	<tr class="table_content">
  		<td>132592859869</td>
  		<td>20</td>
  		<td><p style="color:red; font-weight:bold">3</p></td>
  		<td><button class="btn btn-default">開始加工</button> <button class="btn btn-warning">回報問題</button></td>
  	</tr>
  </table>
  
  <p class="lead" id="doing">加工中</p>
  <div class="table-responsive">
      <table class="table table-hover">
      	<tr class="table_header">
      		<td style="width:10%">圖號</td>
      		<td style="width:8%">剩餘</td>
      		<td style="width:9%">加工機</td>      		   
      		<td style="width:9%">負責人</td>
      		<td style="width:10%">開始於</td>
      		<td style="width:10%">最後更新</td>
      		<td style="width:25%">狀況</td>
          <td></td>
      	</tr>
      	
      	<tr class="table_content">
      		<td>1325928<p id="enhanced_text">59869</p></td>
      		<td style="font-size:24px;"><sup id="enhanced_text">3</sup>&frasl;<sub>20</sub></td>
      		<td>
      			<select class="form-control">
				  <option>內徑1</option>
				  <option>內徑2</option>
				  <option>內徑3</option>
				  <option>內徑4</option>
				  <option>內徑5</option>
				</select>
      		</td>
      		<td>
      			<select class="form-control">
				  <option>志翰</option>
				  <option>君翰</option>
				  <option>老師傅</option>
				</select></td>
      		<td><p>11:20</p><p>12.13.2014</p></td>
      		<td><p>14:20</p><p>12.13.2014</p></td>
      		<td><textarea class="form-control" rows="3"></textarea></td>
      		<td><button class="btn btn-primary">編輯資料</button><br><button class="btn btn-success">加工完成</button></td>
      	</tr>
      	<tr class="table_content">
      		<td>1325928<p id="enhanced_text">59869</p></td>
      		<td style="font-size:24px;"><sup id="enhanced_text">3</sup>&frasl;<sub>20</sub></td>
      		<td>
      			<select class="form-control">
				  <option>內徑1</option>
				  <option>內徑2</option>
				  <option>內徑3</option>
				  <option>內徑4</option>
				  <option>內徑5</option>
				</select>
      		</td>
      		<td>
      			<select class="form-control">
				  <option>志翰</option>
				  <option>君翰</option>
				  <option>老師傅</option>
				</select></td>
      		<td><p>11:20</p><p>12.13.2014</p></td>
      		<td><p>14:20</p><p>12.13.2014</p></td>
      		<td><textarea class="form-control" rows="3"></textarea></td>
      		<td><button class="btn btn-primary">編輯資料</button><br><button class="btn btn-success">加工完成</button></td>
      	</tr>
      </table>
  </div>
  
  <p class="lead" id="finished">已完成</p>
  <table class="table table-hover">
  	<tr class="table_header">
  		<td style="width:10%">圖號</td>
  		<td style="width:10%">數量</td>
  		<td style="width:10%">結束於</td>
  		<td style="width:10%">加工機</td>
      <td style="width:10%">負責人</td>
      <td></td>
  	</tr>
  	
  	<tr class="table_content">
  		<td>132592859869</td>
  		<td>20</td>
  		<td><p>16:35</p><p>12.13.2014</p></td>
      <td>內徑3</td>
      <td>志翰</td>
  		<td><button class="btn btn-warning">回報問題</button></td>
  	</tr>
  	
  </table>
</div>

app/views/processings/new.html.erb
<h1>Processings#new</h1>
<p>Find me in app/views/processings/new.html.erb</p>

app/views/processings/show.html.erb
<h1>Processings#show</h1>
<p>Find me in app/views/processings/show.html.erb</p>

app/views/processings/update.html.erb
<h1>Processings#update</h1>
<p>Find me in app/views/processings/update.html.erb</p>

app/views/stocks/create.html.erb
<h1>Stocks#create</h1>
<p>Find me in app/views/stocks/create.html.erb</p>

app/views/stocks/destroy.html.erb
<h1>Stocks#destroy</h1>
<p>Find me in app/views/stocks/destroy.html.erb</p>

app/views/stocks/edit.html.erb
<h1>Stocks#edit</h1>
<p>Find me in app/views/stocks/edit.html.erb</p>

app/views/stocks/index.html.erb
<div class="container" id="wrap">
  <div class="page-header">
    <h1>帥哥倉庫管理</h1>
  </div>
  <div class="header lead" id="wait">待出貨</div>
  <table class="table table-hover">
  	<tr class="table_header">
  		<td style="width:10%">圖號</td>
  		<td style="width:10%">數量</td>
  		<td style="width:10%">期限</td>
  		<td style="width:70%"></td>
  	</tr>
  	<tr class="table_content">
  		<td>132592859869</td>
  		<td>20</td>
  		<td><p style="color:red; font-weight:bold">3</p></td><td><button class="btn btn-default">開始包裝</button> <button class="btn btn-warning">回報問題</button></td>
  	</tr>
  </table>
  
  <p class="lead" id="doing">包裝中</p>
  <div class="table-responsive">
      <table class="table table-hover">
      	<tr class="table_header">
      		<td style="width:10%">圖號</td>
      		<td style="width:8%">位置</td>   		   
      		<td style="width:9%">負責人</td>
      		<td style="width:10%">開始於</td>
      		<td style="width:10%">最後更新</td>
      		<td style="width:25%">狀況</td>
      		<td></td>
      	</tr>
      	
      	<tr class="table_content">
      		<td>1325928<p id="enhanced_text">59869</p></td>
      		<td id="enhanced_text">A箱</td>
      		<td>
      			<select class="form-control">
				  <option>文清</option>
				  <option>阿輝</option>
				  <option>丁丁</option>
				</select></td>
      		<td><p>11:20</p><p>12.13.2014</p></td>
      		<td><p>14:20</p><p>12.13.2014</p></td>
      		<td><textarea class="form-control" rows="3"></textarea></td>
      		<td><button class="btn btn-success">包裝完成</button> <button class="btn btn-warning">回報問題</button></td>
      	</tr>
      	<tr class="table_content">
      		<td>1325928<p id="enhanced_text">59869</p></td>
      		<td id="enhanced_text">B箱</td>
      		<td>
      			<select class="form-control">
          <option>文清</option>
          <option>阿輝</option>
          <option>丁丁</option>
				</select></td>
      		<td><p>11:20</p><p>12.13.2014</p></td>
      		<td><p>14:20</p><p>12.13.2014</p></td>
      		<td><textarea class="form-control" rows="3"></textarea></td>
      		<td><button class="btn btn-success">包裝完成</button> <button class="btn btn-warning">回報問題</button></td>
      	</tr>
      </table>
  </div>
   
  <p class="lead" id="finished">已包裝完成</p>
  <table class="table table-hover">
    <tr class="table_header">
      <td style="width:10%">圖號</td>
      <td style="width:10%">數量</td>
      <td style="width:10%">結束於</td>
      <td style="width:10%">位置</td>
      <td style="width:10%">負責人</td>
      <td></td>
    </tr>
    
    <tr class="table_content">
      <td>132592859869</td>
      <td>20</td>
      <td><p>16:35</p><p>12.13.2014</p></td>
      <td>B箱</td>
      <td>文清</td>
      <td><button class="btn btn-warning">回報問題</button></td>
    </tr>
    
  </table>
</div>

app/views/stocks/new.html.erb
<h1>Stocks#new</h1>
<p>Find me in app/views/stocks/new.html.erb</p>

app/views/stocks/show.html.erb
<h1>Stocks#show</h1>
<p>Find me in app/views/stocks/show.html.erb</p>

app/views/stocks/update.html.erb
<h1>Stocks#update</h1>
<p>Find me in app/views/stocks/update.html.erb</p>